In [5]:
!pip install pywget
!pip install opencv-python
!pip install wget


In [2]:

import wget
import cv2
import glob
import numpy as np

img=[]
for file in glob.glob('imagenperros.jpg'):
    img.append(cv2.imread(file))

idx=0
print('Shape:{}'.format(img[idx].shape))
# Los dos primeros indices representan el pixel i,j 
# el último indice representa el canal (BGR)
print(img[idx])


Shape:(576, 1024, 3)
[[[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 ...

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]]


In [3]:

cv2.imshow('imagenperros.jpg', img[idx])
cv2.waitKey(0) 
cv2.destroyAllWindows() 

def view(img):
    cv2.imshow("imagenperros.jpg", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

view(img[0])






In [4]:
gris = cv2.cvtColor(img[idx], cv2.COLOR_BGR2GRAY)
gradiente_x,gradiente_y=np.gradient(gris) 
mag_gradiente=np.sqrt(gradiente_x**2+gradiente_y**2)
view(mag_gradiente/np.max(mag_gradiente))

In [ ]:
img_1=img[0]

hsv = cv2.cvtColor(img_1, cv2.COLOR_BGR2HSV)
lower_puppy = np.array([5, 0, 250])  # Baja saturación, alta luminosidad
upper_puppy = np.array([180, 50, 255])
mask = cv2.inRange(hsv, lower_puppy, upper_puppy)
puppy = cv2.bitwise_and(img_1, img_1, mask=mask)
kernel = np.ones((5,5), np.uint8)

mask_clean = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

contours, _ = cv2.findContours(mask_clean, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)






Proceso completado.


In [ ]:
#view(mask_clean)

#y=0
#h=192
#w=205
puppy_list=[]
for j in 3:
    x=0
    for i in 5:
        if contours:
            largest_contour=max(contours,key=cv2.contourArea)
            x,y,w,h=cv2.boundingRect(largest_contour)
            puppy_extracted = img_1[y:y+h, x:x+w]
            puppy_list.append(puppy_extracted)
            x+=w
        y+=h
        if w > 1024:
            w = 1024




        
    


# Crear una imagen con fondo transparente
transparent_bg = np.zeros((h, w, 4), dtype=np.uint8)
transparent_bg[:, :, 3] = 255


#puppy_mask = mask_clean[y:y+h, x:x+w]
#transparent_bg[:, :, :3] = puppy_extracted
#transparent_bg[:, :, 3] = puppy_mask

# Mostrar la imagen resultante
#cv2.imshow('Cachorro recortado', transparent_bg)
#cv2.waitKey(0)
#cv2.destroyAllWindows()


